function ptmdfpv(varargin);
% ptmdfpv( [...] );
% Power Volts 28
h = timeplot({'V28_V1','V28_V2'}, ...
      'Power Volts 28', ...
      'Volts 28', ...
      {'V28\_V1','V28\_V2'}, ...
      varargin{:} );
